---
title: "Create and Publish Websites with Quarto"
author: "Ruslan Khafizov"
format: revealjs
subtitle: "Using GHA Upload"
---

## Overview

- Quarto Pub
- GitHub Pages
    - Render to `docs`
    - `quarto publish`
    - GitHub Action
        - quarto-actions
        - deploy-pages


## Quarto Pub

Just works.
Can set up as a default page.

## GH Pages render to docs

Requires 2 config changes and 2 actions.

- Change _quarto.yml
- Render `doc`
- Push `doc` to GH
- Change GH config to display `doc`

---

### Change _quarto.yml

```{.yaml code-line-numbers="3"}
project:
  type: website
  output-dir: docs
```

---

### Render `doc`

```{.bash}
quarto render
```

---

### Push rendered site to GH

```{.bash}
git add docs
git commit -m "Publish site to docs/"
git push
```

---

### Change GH pages config

Live Demo.

::: aside
Reminder: change Title Slide
:::

## GH Pages quarto publish

Requires config change, one one-off action and one action to publish.

- Set up gh-pages branch (one-off)
- Change GH config to display `gh-pages` branch
- `quarto publish gh-pages`

---

### Set up gh-pages branch

```{.bash}
git checkout --orphan gh-pages
git reset --hard # make sure all changes are committed before running this!
git commit --allow-empty -m "Initialising gh-pages branch"
git push origin gh-pages
```

---

### Change GH config to display `gh-pages` branch

Live demo

---

### `quarto publish gh-pages`

```{.bash}
quarto publish gh-pages
```

## GH Pages GH Actions quarto-actions

Requires config change,

- Set up gh-pages branch (one-off)
- Change GH config to display `gh-pages` branch
- GH Actions `quarto publish gh-pages`

---

### GHA yaml - triggers

```{.yaml}
on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches:
      - main
```

---

### GHA yaml - dependencies and freeze

```{.yaml}
- name: Install R
  uses: r-lib/actions/setup-r@v2
  with:
    r-version: '4.4.1'

- name: Install R Dependencies
  uses: r-lib/actions/setup-renv@v2
  with:
    cache-version: 1
```

---

### Live demo: dependencies and freeze


## I use this graph to trigger freeze

```{r}
#| label: fig-airquality
#| fig-cap: "Temperature and ozone level."
#| warning: false

library(ggplot2)

ggplot(airquality, aes(Temp, Ozone)) + 
  geom_point() + 
  geom_smooth(method = "loess")
```


## GH Pages GH Actions deploy-pages (Bonus)

Requires config change,

- Change GH pages source to `GitHub Actions`
- GH Actions `deploy-pages`

---

### GHA yaml - dependencies and freeze

```{.yaml}
- run: quarto render

- name: Setup Pages
  uses: actions/configure-pages@v5

- name: Upload artifact
  uses: actions/upload-pages-artifact@v3
  if: github.event_name != 'pull_request'
  with:
    path: '_site/'

- name: Deploy to GitHub Pages
  id: deployment
  uses: actions/deploy-pages@v4
  if: github.event_name != 'pull_request'
```